// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSIlhNffh-QA2wv4Ly0_rmPnELVD37ffk',
    appId: '1:788122882566:web:f01c686740fafe547b6987',
    messagingSenderId: '788122882566',
    projectId: 'samplefirebase-88eb6',
    authDomain: 'samplefirebase-88eb6.firebaseapp.com',
    storageBucket: 'samplefirebase-88eb6.firebasestorage.app',
    measurementId: 'G-X74GS5W1WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa6evTBcEuf50ignu-QarnzXPvjByHZkI',
    appId: '1:788122882566:android:69491f7e729762407b6987',
    messagingSenderId: '788122882566',
    projectId: 'samplefirebase-88eb6',
    storageBucket: 'samplefirebase-88eb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4rzZIaXVFKghvTjc00y28ULExqwn3-cI',
    appId: '1:788122882566:ios:9eb5954e8c67b8027b6987',
    messagingSenderId: '788122882566',
    projectId: 'samplefirebase-88eb6',
    storageBucket: 'samplefirebase-88eb6.firebasestorage.app',
    iosBundleId: 'com.example.sampleFirebase',
  );
}
